//! Raw, unsafe bindings to the X-Plane plugin SDK 4.3, generated by bindgen.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/xplm.rs"));
